name: main Workflow
on: [push]
jobs:
 main:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: install dependencies
          uses: shivammathur/setup-php@v2
          with:
                php-version: '8.1'
                tools: phpcs, phpunit
        - name: Linter Test
          run: make lint
        - name: PhpUnit Test
          run: make lint
